### ISSUE TITLE
upgrade version to 3.0.1.18

### ISSUE THREAD

**Issue by zqhxuyuan** [graphaware/graphaware-starter#1]
the project's version is 2.x, when  I upgrade to version 3.0.1.18, there are some error on FriendshipStrengthModule:
1. GlobalGraphOperations seems disappear

2.for (Node counter : Iterables.asResourceIterable(database.findNodes(Labels.FriendshipCounter)))
 type error

can some guys fix this?

**Comment by ikwattro** [comment]
Thanks, we will upgrade.

**Comment by ikwattro** [comment]
@zqhxuyuan Fixed by #2 . Waiting for merge

**Comment by zqhxuyuan** [comment]
tks!
